name: 1.0.$(Date:yyyy-mm-dd).$(rev:r)

trigger:
  batch: true
  branches:
    include:
      - pr
      - master
  
stages:
  - stage: Build
    displayName: Build Dacpac
    jobs:
      - job: Dacpac
        steps:
          - task: DotNetCoreCLI@2 
            inputs:
              configuration: release
              command: build
              projects: '**/*.sqlproj'
              modifyOutputPath: .
          - task: PublishBuildArtifacts@1
            inputs:
              publishLocation: FilePath
              ArtifactName: boh-schema.dacpac
              PathtoPublish: $(System.DefaultWorkingDirectory)/**/*.dacpac


